chore: increase depth for correct git push

diff --git a/.github/workflows/res-update-game.yml b/.github/workflows/res-update-game.yml
--- a/.github/workflows/res-update-game.yml
+++ b/.github/workflows/res-update-game.yml
@@ -104,14 +104,14 @@ jobs:
           parameters=("CN" "US" "JP" "KR")
 
           for param in "${parameters[@]}"; do
-              {
-                  if curl -s -o "stages_${param}.json" "${baseUrl}${param}"; then
-                      echo "Successfully fetched data for ${param}"
-                  else
-                      echo "Failed to fetch data for ${param}" >&2
-                      exit 1
-                  fi
-              } &
+            {
+              if curl -s -o "stages_${param}.json" "${baseUrl}${param}"; then
+                echo "Successfully fetched data for ${param}"
+              else
+                echo "Failed to fetch data for ${param}" >&2
+                exit 1
+              fi
+            } &
           done
           wait
 
@@ -132,7 +132,7 @@ jobs:
           # actions/checkout uses ${{ secrets.GITHUB_TOKEN }} by default, meaning all steps will inherit it
           persist-credentials: false # Needed to bypass protection rules in Push changes
           show-progress: false
-          fetch-depth: 2
+          fetch-depth: 3
 
       - name: Restore ResourceUpdater.exe from cache
         id: cache-resupd
