perf: moved penguin to txwy workflow + thread error management

diff --git a/.github/workflows/res-update-game.yml b/.github/workflows/res-update-game.yml
--- a/.github/workflows/res-update-game.yml
+++ b/.github/workflows/res-update-game.yml
@@ -35,26 +35,6 @@ jobs:
             /gamedata/excel/roguelike_topic_table.json
             /gamedata/excel/activity_table.json
 
-      - name: Download stages.json from Penguin Stats
-        run: |
-          cd "./Official"
-
-          baseUrl="https://penguin-stats.io/PenguinStats/api/v2/stages?server="
-
-          parameters=("CN" "US" "JP" "KR")
-
-          for param in "${parameters[@]}"; do
-              {
-                  if curl -s -o "stages_${param}.json" "${baseUrl}${param}"; then
-                      echo "Successfully fetched data for ${param}"
-                  else
-                      echo "Failed to fetch data for ${param}" >&2
-                      exit 1
-                  fi
-              } &
-          done
-          wait
-      
       - name: Upload Official
         uses: actions/upload-artifact@v4.3.4
         with:
@@ -114,6 +94,26 @@ jobs:
           ref: data-tw
           path: ./excel
           token: ${{ secrets.ARKNTOOLS_MAA_RESOURCE_UPDATER}}
+
+      - name: Download stages.json from Penguin Stats
+        run: |
+          cd "./excel"
+
+          baseUrl="https://penguin-stats.io/PenguinStats/api/v2/stages?server="
+
+          parameters=("CN" "US" "JP" "KR")
+
+          for param in "${parameters[@]}"; do
+              {
+                  if curl -s -o "stages_${param}.json" "${baseUrl}${param}"; then
+                      echo "Successfully fetched data for ${param}"
+                  else
+                      echo "Failed to fetch data for ${param}" >&2
+                      exit 1
+                  fi
+              } &
+          done
+          wait
 
       - name: Upload Official
         uses: actions/upload-artifact@v4.3.4
