refactor: move penguin stages download to repo download step

diff --git a/.github/workflows/res-update-game.yml b/.github/workflows/res-update-game.yml
--- a/.github/workflows/res-update-game.yml
+++ b/.github/workflows/res-update-game.yml
@@ -35,6 +35,26 @@ jobs:
             /gamedata/excel/roguelike_topic_table.json
             /gamedata/excel/activity_table.json
 
+      - name: Download stages.json from Penguin Stats
+        run: |
+          cd "./Official"
+
+          baseUrl="https://penguin-stats.io/PenguinStats/api/v2/stages?server="
+
+          parameters=("CN" "US" "JP" "KR")
+
+          for param in "${parameters[@]}"; do
+              {
+                  if curl -s -o "stages_${param}.json" "${baseUrl}${param}"; then
+                      echo "Successfully fetched data for ${param}"
+                  else
+                      echo "Failed to fetch data for ${param}" >&2
+                      exit 1
+                  fi
+              } &
+          done
+          wait
+      
       - name: Upload Official
         uses: actions/upload-artifact@v4.3.4
         with:
