ci: Resource Updater push perfs (#10733)
---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/.github/workflows/res-update-game.yml b/.github/workflows/res-update-game.yml
--- a/.github/workflows/res-update-game.yml
+++ b/.github/workflows/res-update-game.yml
@@ -104,14 +104,14 @@ jobs:
           parameters=("CN" "US" "JP" "KR")
 
           for param in "${parameters[@]}"; do
-              {
-                  if curl -s -o "stages_${param}.json" "${baseUrl}${param}"; then
-                      echo "Successfully fetched data for ${param}"
-                  else
-                      echo "Failed to fetch data for ${param}" >&2
-                      exit 1
-                  fi
-              } &
+            {
+              if curl -s -o "stages_${param}.json" "${baseUrl}${param}"; then
+                echo "Successfully fetched data for ${param}"
+              else
+                echo "Failed to fetch data for ${param}" >&2
+                exit 1
+              fi
+            } &
           done
           wait
 
@@ -132,6 +132,7 @@ jobs:
           # actions/checkout uses ${{ secrets.GITHUB_TOKEN }} by default, meaning all steps will inherit it
           persist-credentials: false # Needed to bypass protection rules in Push changes
           show-progress: false
+          fetch-depth: 3
 
       - name: Restore ResourceUpdater.exe from cache
         id: cache-resupd
@@ -194,7 +195,7 @@ jobs:
           Write-Output "gitdiff=$(git diff --name-only --diff-filter=ACM 2>$null | Select-String -Pattern '\.json$' -List)" >> $env:GITHUB_OUTPUT
 
       - name: Run prettier
-        uses: actionsx/prettier@v3
+        uses: Nerixyz/actionsx-prettier@v3-adj
         with:
           args: -w ${{ steps.task_sorting.outputs.gitdiff }}
 
